
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import cafekwae_logo  from './assests/cafekwae_logo.png';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cafe Kwae",
  description: "Generated by create next app",
};



export default function RootLayout({
  

  children,
}: Readonly<{
  children: React.ReactNode;
}>) 


{
  return (
    <html lang="en">
      
      <body className={inter.className}>
        {children}
        
      </body>
    </html>
  );
}
